# Use an official Node runtime as a parent image
FROM node:18

#Set the working directory in the container to /app
#A docker file is the blueprint of a docker image
#A docker image is the blueprint of a container 
#A docker image can be used to instantiate two or more containers
#A container is actually going to run our code within an isolated environment
WORKDIR /app

#Copy package.json and package-lock.json into the working directory
COPY package*.json ./

#Install any packages specified in package.json
RUN npm install

#Install ffmpeg in the container
RUN apt-get update && apt-get install -y ffmpeg

#Copy app source inside the docker image
COPY . .

#Make port 3000 available outside the container
EXPOSE 300

#Define the cmd to start your app using CMD [only one comamnd allowed]
CMD ["npm", "start"]
